default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: marvel_comics_reader_development

test:
  <<: *default
  database: marvel_comics_reader_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: marvel_comics_reader_production
  username: marvel_comics_reader
  password: <%= ENV["MARVEL_COMICS_READER_DATABASE_PASSWORD"] %>
